# Generated by Django 3.1.13 on 2021-08-01 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('time_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on')),
                ('creator_by_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Creator Username')),
                ('modified_by_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modified Username')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Service')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Slug of Service')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description of Service')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_service_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_service_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
